server:
  port: 8080

spring:
  application:
    name: "CrediyaApplicationMicroservice"
  devtools:
    add-properties: false
  jackson:
    time-zone: "America/Bogota"
  profiles:
    active: local # Change to 'prod' for production

security:
  jwt:
    secret: "Vna79qB2rPz6tXhE9fWcK5sJmG3dD8vA"
    expiration-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapter:
  sqs:
    region: "${AWS_REGION}"
    queue-url: "${SQS_QUEUE_URL}"
    validation-queue-url: "${SQS_VALIDATION_QUEUE_URL}"
